// Package cache_dal_single is generated by protoc-gen-go-genms-dal. *DO NOT EDIT*
package cache_dal_single

import "github.com/rleszilm/genms/cache"

//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 -generate

var (
	logs = cache.Logs()
)
