// Package cache_dal_single is generated by protoc-gen-go-genms-dal. *DO NOT EDIT*
package cache_dal_single

import (
	context "context"
	fmt "fmt"
	time "time"

	cache "github.com/rleszilm/genms/cache"
	single "github.com/rleszilm/genms/cmd/protoc-gen-go-genms-dal/example/single"
	service "github.com/rleszilm/genms/service"
	stats "go.opencensus.io/stats"
	tag "go.opencensus.io/tag"
)

// SingleMap defines a Map base cache implementing SingleReadWriter.
// If a key is queries that does not exist an attempt to read and store it is made.
type SingleMap struct {
	service.Dependencies
	UnimplementedSingleCache

	name   string
	reader SingleReader
	writer SingleWriter
	cache  map[SingleKey]*single.Single
	all    []*single.Single
}

// Initialize initializes and starts the service. Initialize should panic in case of
// any errors. It is intended that Initialize be called only once during the service life-cycle.
func (x *SingleMap) Initialize(ctx context.Context) error {
	return nil
}

// Shutdown closes the long-running instance, or service.
func (x *SingleMap) Shutdown(_ context.Context) error {
	return nil
}

// String returns the name of the map.
func (x *SingleMap) String() string {
	if x.name != "" {
		return x.name
	}
	return "cache-dal-single-single-map"
}

// NameOf returns the name of the map.
func (x *SingleMap) NameOf() string {
	return x.String()
}

// All implements implements SingleReadAller.
func (x *SingleMap) All(ctx context.Context) ([]*single.Single, error) {
	start := time.Now()
	ctx, _ = tag.New(ctx,
		tag.Upsert(cache.TagCollection, "single"),
		tag.Upsert(cache.TagInstance, x.name),
		tag.Upsert(cache.TagMethod, "all"),
		tag.Upsert(cache.TagType, "map"),
	)
	stats.Record(ctx, cache.MeasureInflight.M(1))
	defer func() {
		stop := time.Now()
		dur := float64(stop.Sub(start).Nanoseconds()) / float64(time.Millisecond)
		stats.Record(ctx, cache.MeasureLatency.M(dur), cache.MeasureInflight.M(-1))
	}()

	return x.all, nil
}

// Get implements SingleReader.
func (x *SingleMap) Get(ctx context.Context, key SingleKey) (*single.Single, error) {
	start := time.Now()
	ctx, _ = tag.New(ctx,
		tag.Upsert(cache.TagCollection, "single"),
		tag.Upsert(cache.TagInstance, x.name),
		tag.Upsert(cache.TagMethod, "get"),
		tag.Upsert(cache.TagType, "map"),
	)
	stats.Record(ctx, cache.MeasureInflight.M(1))
	defer func() {
		stop := time.Now()
		dur := float64(stop.Sub(start).Nanoseconds()) / float64(time.Millisecond)
		stats.Record(ctx, cache.MeasureLatency.M(dur), cache.MeasureInflight.M(-1))
	}()

	if val, ok := x.cache[key]; ok {
		return val, nil
	}

	if x.reader != nil {
		val, err := x.reader.Get(ctx, key)
		if err != nil {
			return nil, fmt.Errorf("map: Single.Get - %w", err)
		}
		x.cache[key] = val
		return val, nil
	}

	stats.Record(ctx, cache.MeasureError.M(1))
	return nil, fmt.Errorf("map: Single.Get - %w", cache.ErrNoValue)
}

// Set implements SingleWriter.
func (x *SingleMap) Set(ctx context.Context, key SingleKey, val *single.Single) (*single.Single, error) {
	start := time.Now()
	ctx, _ = tag.New(ctx,
		tag.Upsert(cache.TagCollection, "single"),
		tag.Upsert(cache.TagInstance, x.name),
		tag.Upsert(cache.TagMethod, "get"),
		tag.Upsert(cache.TagType, "map"),
	)
	stats.Record(ctx, cache.MeasureInflight.M(1))
	defer func() {
		stop := time.Now()
		dur := float64(stop.Sub(start).Nanoseconds()) / float64(time.Millisecond)
		stats.Record(ctx, cache.MeasureLatency.M(dur), cache.MeasureInflight.M(-1))
	}()

	if x.writer != nil {
		upd, err := x.writer.Set(ctx, key, val)
		if err != nil {
			stats.Record(ctx, cache.MeasureError.M(1))
			return nil, fmt.Errorf("map: Single.Set - %w", err)
		}
		val = upd
	}

	x.cache[key] = val

	all := []*single.Single{}
	for _, v := range x.cache {
		all = append(all, v)
	}
	x.all = all

	return val, nil
}

// WithReader tells the SingleMap where to source values from if they don't exist in cache.
func (x *SingleMap) WithReader(r SingleReader) {
	x.reader = r
}

// WithWriter tells the SingleMap where to source values from if they don't exist in cache.
func (x *SingleMap) WithWriter(w SingleWriter) {
	x.writer = w
}

// NewSingleMap returns a new SingleMap cache.
func NewSingleMap(name string) (*SingleMap, error) {
	return &SingleMap{
		name:  name,
		cache: map[SingleKey]*single.Single{},
	}, nil
}
