// Generated by protoc-gen-go-genms-dal. *DO NOT EDIT*
package dal_users

import (
	context "context"
	errors "errors"
	types "github.com/rleszilm/gen_microservice/cmd/protoc-gen-go-genms-dal/annotations/types"
	users "github.com/rleszilm/gen_microservice/cmd/protoc-gen-go-genms-dal/example/users"
	service "github.com/rleszilm/gen_microservice/service"
	latlng "google.golang.org/genproto/googleapis/type/latlng"
)

var (
	// ErrUserCollectionMethodImpl is returned when the called method is not implemented.
	ErrUserCollectionMethodImpl = errors.New("UserCollection method is not implemented")
)

// UserCollection is an autogenerated interface that can be used to interact with a collection of User objects.
type UserCollection interface {
	service.Service

	UserCollectionReader
	UserCollectionWriter
}

// UserCollectionWriter is an autogenerated interface that can be used to write to a collection of User objects.
type UserCollectionWriter interface {
	Upsert(context.Context, *users.User) (*users.User, error)
}

// UserCollectionReader is an autogenerated interface that can be used to query a collection
// of User objects. The queries and their values are taken from the representative proto message.
type UserCollectionReader interface {
	All(context.Context) ([]*users.User, error)
	Filter(context.Context, *UserFields) ([]*users.User, error)
	ById(context.Context, int64) ([]*users.User, error)
	ByNameAndDivision(context.Context, string, string) ([]*users.User, error)
	ByKind(context.Context, users.User_Kind) ([]*users.User, error)
	ByPhone(context.Context, *types.Phone) ([]*users.User, error)
	ProviderStubOnly(context.Context) ([]*users.User, error)
	InterfaceStubOnly(context.Context) ([]*users.User, error)
}

// UserFields is an autogenerated struct that can be used in the generic queries against UserCollection.
type UserFields struct {
	Id               *int64
	Name             *string
	Division         *string
	LifetimeScore    *float64
	LastScore        *float32
	LifetimeWinnings *int64
	LastWinnings     *int32
	Point            *types.Point
	Phone            *types.Phone
	Geo              *latlng.LatLng
	Kind             *users.User_Kind
	ByBackend        *string
}

// UnimplementedUserCollection is an autogenerated implementation of UserCollection that returns an error when any
// method is called.
type UnimplementedUserCollection struct {
	service.Deps
}

// Upsert implements UserCollection.Upsert
func (x *UnimplementedUserCollection) Upsert(_ context.Context, _ *users.User) (*users.User, error) {
	return nil, ErrUserCollectionMethodImpl
}

// Filter implements UserCollection.Filter
func (x *UnimplementedUserCollection) Filter(_ context.Context, _ *UserFields) ([]*users.User, error) {
	return nil, ErrUserCollectionMethodImpl
}

// ById implements UserCollection.ById
func (x *UnimplementedUserCollection) ById(_ context.Context, _ int64) ([]*users.User, error) {
	return nil, ErrUserCollectionMethodImpl
}

// ByNameAndDivision implements UserCollection.ByNameAndDivision
func (x *UnimplementedUserCollection) ByNameAndDivision(_ context.Context, _ string, _ string) ([]*users.User, error) {
	return nil, ErrUserCollectionMethodImpl
}

// ByKind implements UserCollection.ByKind
func (x *UnimplementedUserCollection) ByKind(_ context.Context, _ users.User_Kind) ([]*users.User, error) {
	return nil, ErrUserCollectionMethodImpl
}

// ByPhone implements UserCollection.ByPhone
func (x *UnimplementedUserCollection) ByPhone(_ context.Context, _ *types.Phone) ([]*users.User, error) {
	return nil, ErrUserCollectionMethodImpl
}

// ProviderStubOnly implements UserCollection.ProviderStubOnly
func (x *UnimplementedUserCollection) ProviderStubOnly(_ context.Context) ([]*users.User, error) {
	return nil, ErrUserCollectionMethodImpl
}

// InterfaceStubOnly implements UserCollection.InterfaceStubOnly
func (x *UnimplementedUserCollection) InterfaceStubOnly(_ context.Context) ([]*users.User, error) {
	return nil, ErrUserCollectionMethodImpl
}
