// Package users is generated by protoc-gen-go-genms-dal. *DO NOT EDIT*
package users

import (
	context "context"
	errors "errors"
	types "github.com/rleszilm/genms/cmd/protoc-gen-go-genms-dal/annotations/types"
	users "github.com/rleszilm/genms/cmd/protoc-gen-go-genms-dal/example/users"
	service "github.com/rleszilm/genms/service"
	latlng "google.golang.org/genproto/googleapis/type/latlng"
)

var (
	// ErrUserCollectionMethodImpl is returned when the called method is not implemented.
	ErrUserCollectionMethodImpl = errors.New("UserCollection method is not implemented")
)

// UserCollection is an autogenerated interface that can be used to interact with a collection of User objects.
//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . UserCollection
type UserCollection interface {
	service.Service

	UserCollectionReader
	UserCollectionWriter
}

// UserCollectionWriter is an autogenerated interface that can be used to write to a collection of User objects.
//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . UserCollectionWriter
type UserCollectionWriter interface {
	Insert(context.Context, *users.User) (*users.User, error)
	Upsert(context.Context, *users.User) (*users.User, error)
}

// UserCollectionReader is an autogenerated interface that can be used to query a collection
// of User objects. The queries and their values are taken from the representative proto message.
//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . UserCollectionReader
type UserCollectionReader interface {
	All(context.Context) ([]*users.User, error)
	Filter(context.Context, *UserFilter) ([]*users.User, error)
}

// UserFilter is an autogenerated struct that can be used in the generic queries against UserCollection.
type UserFilter struct {
	Id            *int64
	Name          *string
	Division      *string
	LifetimeScore *float64
	LastScore     *float32
	LastWinnings  *int32
	Point         *types.Point
	Phone         *types.Phone
	Geo           *latlng.LatLng
	Kind          *users.User_Kind
	ByBackend     *string
}
