// Package mongo_dal_single is generated by protoc-gen-go-genms-dal. *DO NOT EDIT*
package mongo_dal_single

//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 -generate

var (
	logs = logs
)
