// Package dal_multi is generated by protoc-gen-go-genms-dal. *DO NOT EDIT*
package dal_multi

import (
	context "context"
	errors "errors"
	fmt "fmt"
	multi "github.com/rleszilm/genms/cmd/protoc-gen-go-genms-dal/example/multi"
	service "github.com/rleszilm/genms/service"
)

var (
	// ErrTypeTwoCollectionMethodImpl is returned when the called method is not implemented.
	ErrTypeTwoCollectionMethodImpl = errors.New("TypeTwoCollection method is not implemented")
)

// TypeTwoMutator is a function that makes changes to a TypeTwo.
type TypeTwoMutator func(*multi.TypeTwo) (*multi.TypeTwo, error) // TypeTwoCollection is an autogenerated interface that can be used to interact with a collection of TypeTwo objects.
//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . TypeTwoCollection
type TypeTwoCollection interface {
	service.Service

	TypeTwoCollectionReader
	TypeTwoCollectionWriter
}

// TypeTwoCollectionWriter is an autogenerated interface that can be used to write to a collection of TypeTwo objects.
//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . TypeTwoCollectionWriter
type TypeTwoCollectionWriter interface {
	// Insert runs the command to generate a new object within the data store.
	Insert(context.Context, *multi.TypeTwo) (*multi.TypeTwo, error)
	// Upsert runs the command to overwrite the object in the datastore, or write it if it does not already exist.
	Upsert(context.Context, *multi.TypeTwo) (*multi.TypeTwo, error)
	// Update runs the command to make changes to the given record.
	Update(context.Context, *multi.TypeTwo, *TypeTwoFieldValues) (*multi.TypeTwo, error)
}

// TypeTwoCollectionReader is an autogenerated interface that can be used to query a collection
// of TypeTwo objects. The queries and their values are taken from the representative proto message.
//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . TypeTwoCollectionReader
type TypeTwoCollectionReader interface {
	All(context.Context) ([]*multi.TypeTwo, error)
	Filter(context.Context, *TypeTwoFieldValues) ([]*multi.TypeTwo, error)
	OneParam(_ context.Context, _ int32) ([]*multi.TypeTwo, error)
	MultipleParam(_ context.Context, _ int32, _ int64, _ float32) ([]*multi.TypeTwo, error)
	MessageParam(_ context.Context, _ *multi.TypeTwo_Message) ([]*multi.TypeTwo, error)
	WithComparator(_ context.Context, _ int32) ([]*multi.TypeTwo, error)
	WithRest(_ context.Context, _ int32, _ int64, _ float32, _ float64) ([]*multi.TypeTwo, error)
	ProviderStubOnly(_ context.Context) ([]*multi.TypeTwo, error)
	InterfaceStubOnly(_ context.Context) ([]*multi.TypeTwo, error)
}

// TypeTwoFieldValues is an autogenerated struct that can be used in the generic queries against TypeTwoCollection.
type TypeTwoFieldValues struct {
	ScalarInt32     *int32
	ScalarInt64     *int64
	ScalarFloat32   *float32
	ScalarFloat64   *float64
	ScalarString    *string
	ScalarBool      *bool
	ScalarEnum      *multi.TypeTwo_Enum
	ObjMessage      *multi.TypeTwo_Message
	Renamed         *string
	IgnoredPostgres *string
	RenamedPostgres *string
	IgnoredRest     *string
	RenamedRest     *string
}

// UnimplementedTypeTwoCollection is an autogenerated implementation of TypeTwoCollection that returns an error when any
// method is called.
type UnimplementedTypeTwoCollection struct {
	service.Dependencies
}

// Insert implements TypeTwoCollection.Insert
func (x *UnimplementedTypeTwoCollection) Insert(_ context.Context, _ *multi.TypeTwo) (*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

// Upsert implements TypeTwoCollection.Upsert
func (x *UnimplementedTypeTwoCollection) Upsert(_ context.Context, _ *multi.TypeTwo) (*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

// Update implements TypeTwoCollection.Update
func (x *UnimplementedTypeTwoCollection) Update(_ context.Context, _ *multi.TypeTwo, _ *TypeTwoFieldValues) (*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

// Filter implements TypeTwoCollection.Filter
func (x *UnimplementedTypeTwoCollection) Filter(_ context.Context, _ *TypeTwoFieldValues) ([]*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

// OneParam implements TypeTwoCollection.OneParam
func (x *UnimplementedTypeTwoCollection) OneParam(_ context.Context, _ int32) ([]*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

// MultipleParam implements TypeTwoCollection.MultipleParam
func (x *UnimplementedTypeTwoCollection) MultipleParam(_ context.Context, _ int32, _ int64, _ float32) ([]*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

// MessageParam implements TypeTwoCollection.MessageParam
func (x *UnimplementedTypeTwoCollection) MessageParam(_ context.Context, _ *multi.TypeTwo_Message) ([]*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

// WithComparator implements TypeTwoCollection.WithComparator
func (x *UnimplementedTypeTwoCollection) WithComparator(_ context.Context, _ int32) ([]*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

// WithRest implements TypeTwoCollection.WithRest
func (x *UnimplementedTypeTwoCollection) WithRest(_ context.Context, _ int32, _ int64, _ float32, _ float64) ([]*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

// ProviderStubOnly implements TypeTwoCollection.ProviderStubOnly
func (x *UnimplementedTypeTwoCollection) ProviderStubOnly(_ context.Context) ([]*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

// InterfaceStubOnly implements TypeTwoCollection.InterfaceStubOnly
func (x *UnimplementedTypeTwoCollection) InterfaceStubOnly(_ context.Context) ([]*multi.TypeTwo, error) {
	return nil, ErrTypeTwoCollectionMethodImpl
}

func ReturnsOneTypeTwo(xs []*multi.TypeTwo, err error) (*multi.TypeTwo, error) {
	if err != nil {
		return nil, err
	}

	switch len(xs) {
	case 0:
		return nil, err
	case 1:
		return xs[0], err
	default:
		return nil, fmt.Errorf("multi.typetwo: more than 1 value returned - %w", err)
	}
}
