// Package cache_dal_multi is generated by protoc-gen-go-genms-dal. *DO NOT EDIT*
package cache_dal_multi

import (
	context "context"
	fmt "fmt"
	time "time"

	cache "github.com/rleszilm/genms/cache"
	multi "github.com/rleszilm/genms/cmd/protoc-gen-go-genms-dal/example/multi"
	service "github.com/rleszilm/genms/service"
	stats "go.opencensus.io/stats"
	tag "go.opencensus.io/tag"
)

// TypeTwoMap defines a Map base cache implementing TypeTwoReadWriter.
// If a key is queries that does not exist an attempt to read and store it is made.
type TypeTwoMap struct {
	service.Dependencies
	UnimplementedTypeTwoCache

	name   string
	reader TypeTwoReader
	writer TypeTwoWriter
	cache  map[TypeTwoKey]*multi.TypeTwo
	all    []*multi.TypeTwo
}

// Initialize initializes and starts the service. Initialize should panic in case of
// any errors. It is intended that Initialize be called only once during the service life-cycle.
func (x *TypeTwoMap) Initialize(ctx context.Context) error {
	return nil
}

// Shutdown closes the long-running instance, or service.
func (x *TypeTwoMap) Shutdown(_ context.Context) error {
	return nil
}

// String returns the name of the map.
func (x *TypeTwoMap) String() string {
	if x.name != "" {
		return x.name
	}
	return "cache-dal-multi-type-two-map"
}

// NameOf returns the name of the map.
func (x *TypeTwoMap) NameOf() string {
	return x.String()
}

// All implements implements TypeTwoReadAller.
func (x *TypeTwoMap) All(ctx context.Context) ([]*multi.TypeTwo, error) {
	start := time.Now()
	ctx, _ = tag.New(ctx,
		tag.Upsert(cache.TagCollection, "type_two"),
		tag.Upsert(cache.TagInstance, x.name),
		tag.Upsert(cache.TagMethod, "all"),
		tag.Upsert(cache.TagType, "map"),
	)
	stats.Record(ctx, cache.MeasureInflight.M(1))
	defer func() {
		stop := time.Now()
		dur := float64(stop.Sub(start).Nanoseconds()) / float64(time.Millisecond)
		stats.Record(ctx, cache.MeasureLatency.M(dur), cache.MeasureInflight.M(-1))
	}()

	return x.all, nil
}

// Get implements TypeTwoReader.
func (x *TypeTwoMap) Get(ctx context.Context, key TypeTwoKey) (*multi.TypeTwo, error) {
	start := time.Now()
	ctx, _ = tag.New(ctx,
		tag.Upsert(cache.TagCollection, "type_two"),
		tag.Upsert(cache.TagInstance, x.name),
		tag.Upsert(cache.TagMethod, "get"),
		tag.Upsert(cache.TagType, "map"),
	)
	stats.Record(ctx, cache.MeasureInflight.M(1))
	defer func() {
		stop := time.Now()
		dur := float64(stop.Sub(start).Nanoseconds()) / float64(time.Millisecond)
		stats.Record(ctx, cache.MeasureLatency.M(dur), cache.MeasureInflight.M(-1))
	}()

	if val, ok := x.cache[key]; ok {
		return val, nil
	}

	if x.reader != nil {
		val, err := x.reader.Get(ctx, key)
		if err != nil {
			return nil, fmt.Errorf("map: TypeTwo.Get - %w", err)
		}
		x.cache[key] = val
		return val, nil
	}

	stats.Record(ctx, cache.MeasureError.M(1))
	return nil, fmt.Errorf("map: TypeTwo.Get - %w", cache.ErrNoValue)
}

// Set implements TypeTwoWriter.
func (x *TypeTwoMap) Set(ctx context.Context, key TypeTwoKey, val *multi.TypeTwo) (*multi.TypeTwo, error) {
	start := time.Now()
	ctx, _ = tag.New(ctx,
		tag.Upsert(cache.TagCollection, "type_two"),
		tag.Upsert(cache.TagInstance, x.name),
		tag.Upsert(cache.TagMethod, "get"),
		tag.Upsert(cache.TagType, "map"),
	)
	stats.Record(ctx, cache.MeasureInflight.M(1))
	defer func() {
		stop := time.Now()
		dur := float64(stop.Sub(start).Nanoseconds()) / float64(time.Millisecond)
		stats.Record(ctx, cache.MeasureLatency.M(dur), cache.MeasureInflight.M(-1))
	}()

	if x.writer != nil {
		upd, err := x.writer.Set(ctx, key, val)
		if err != nil {
			stats.Record(ctx, cache.MeasureError.M(1))
			return nil, fmt.Errorf("map: TypeTwo.Set - %w", err)
		}
		val = upd
	}

	x.cache[key] = val

	all := []*multi.TypeTwo{}
	for _, v := range x.cache {
		all = append(all, v)
	}
	x.all = all

	return val, nil
}

// WithReader tells the TypeTwoMap where to source values from if they don't exist in cache.
func (x *TypeTwoMap) WithReader(r TypeTwoReader) {
	x.reader = r
}

// WithWriter tells the TypeTwoMap where to source values from if they don't exist in cache.
func (x *TypeTwoMap) WithWriter(w TypeTwoWriter) {
	x.writer = w
}

// NewTypeTwoMap returns a new TypeTwoMap cache.
func NewTypeTwoMap(name string) (*TypeTwoMap, error) {
	return &TypeTwoMap{
		name:  name,
		cache: map[TypeTwoKey]*multi.TypeTwo{},
	}, nil
}
