// Package cache_dal_single is generated by protoc-gen-go-genms-dal. *DO NOT EDIT*
package cache_dal_single

import (
	context "context"
	fmt "fmt"
	time "time"

	golang_lru "github.com/hashicorp/golang-lru"
	cache "github.com/rleszilm/genms/cache"
	single "github.com/rleszilm/genms/cmd/protoc-gen-go-genms-dal/example/single"
	keyvalue "github.com/rleszilm/genms/cmd/protoc-gen-go-genms-dal/example/single/dal/keyvalue"
	service "github.com/rleszilm/genms/service"
	stats "go.opencensus.io/stats"
	tag "go.opencensus.io/tag"
)

// SingleLRU defines a LRU cache implementing keyvalue.SingleReadWriter.
// If a key is queries that does not exist an attempt to read and store it is made.
type SingleLRU struct {
	service.Dependencies
	NilSingleCache

	name   string
	reader keyvalue.SingleReader
	writer keyvalue.SingleWriter
	lru    *golang_lru.ARCCache
	all    []*single.Single
}

// Initialize initializes and starts the service. Initialize should panic in case of
// any errors. It is intended that Initialize be called only once during the service life-cycle.
func (x *SingleLRU) Initialize(ctx context.Context) error {
	return nil
}

// Shutdown closes the long-running instance, or service.
func (x *SingleLRU) Shutdown(_ context.Context) error {
	return nil
}

// String returns the name of the LRU.
func (x *SingleLRU) String() string {
	if x.name != "" {
		return "cache-dal-single-single-lru-" + x.name
	}
	return "cache-dal-single-single-lru"
}

// NameOf returns the name of the LRU.
func (x *SingleLRU) NameOf() string {
	return x.String()
}

// All implements implements keyvalue.SingleReadAller.
func (x *SingleLRU) All(ctx context.Context) ([]*single.Single, error) {
	start := time.Now()
	ctx, _ = tag.New(ctx,
		tag.Upsert(cache.TagCollection, "single"),
		tag.Upsert(cache.TagInstance, x.name),
		tag.Upsert(cache.TagMethod, "all"),
		tag.Upsert(cache.TagType, "lru"),
	)
	stats.Record(ctx, cache.MeasureInflight.M(1))
	defer func() {
		stop := time.Now()
		dur := float64(stop.Sub(start).Nanoseconds()) / float64(time.Millisecond)
		stats.Record(ctx, cache.MeasureLatency.M(dur), cache.MeasureInflight.M(-1))
	}()

	return x.all, nil
}

// GetByKey implements keyvalue.SingleReader.
func (x *SingleLRU) GetByKey(ctx context.Context, key keyvalue.SingleKey) (*single.Single, error) {
	start := time.Now()
	ctx, _ = tag.New(ctx,
		tag.Upsert(cache.TagCollection, "single"),
		tag.Upsert(cache.TagInstance, x.name),
		tag.Upsert(cache.TagMethod, "get"),
		tag.Upsert(cache.TagType, "lru"),
	)
	stats.Record(ctx, cache.MeasureInflight.M(1))
	defer func() {
		stop := time.Now()
		dur := float64(stop.Sub(start).Nanoseconds()) / float64(time.Millisecond)
		stats.Record(ctx, cache.MeasureLatency.M(dur), cache.MeasureInflight.M(-1))
	}()

	if val, ok := x.lru.Get(key); ok {
		stats.Record(ctx, cache.MeasureHit.M(1))
		return val.(*single.Single), nil
	}
	stats.Record(ctx, cache.MeasureMiss.M(1))

	if x.reader != nil {
		val, err := x.reader.GetByKey(ctx, key)
		if err != nil {
			return nil, fmt.Errorf("lru: Single.GetByKey - %w", err)
		}
		x.lru.Add(key, val)
		return val, nil
	}

	stats.Record(ctx, cache.MeasureError.M(1))
	return nil, fmt.Errorf("lru: Single.GetByKey - %w", cache.ErrGetValue)
}

// SetByKey implements keyvalue.SingleWriter.
func (x *SingleLRU) SetByKey(ctx context.Context, key keyvalue.SingleKey, val *single.Single) (*single.Single, error) {
	start := time.Now()
	ctx, _ = tag.New(ctx,
		tag.Upsert(cache.TagCollection, "single"),
		tag.Upsert(cache.TagInstance, x.name),
		tag.Upsert(cache.TagMethod, "set"),
		tag.Upsert(cache.TagType, "lru"),
	)
	stats.Record(ctx, cache.MeasureInflight.M(1))
	defer func() {
		stop := time.Now()
		dur := float64(stop.Sub(start).Nanoseconds()) / float64(time.Millisecond)
		stats.Record(ctx, cache.MeasureLatency.M(dur), cache.MeasureInflight.M(-1))
	}()

	if x.writer != nil {
		upd, err := x.writer.SetByKey(ctx, key, val)
		if err != nil {
			stats.Record(ctx, cache.MeasureError.M(1))
			return nil, fmt.Errorf("lru: Single.SetBykey - %w", err)
		}
		val = upd
	}

	x.lru.Add(key, val)

	all := []*single.Single{}
	for _, k := range x.lru.Keys() {
		y, _ := x.lru.Get(k)
		all = append(all, y.(*single.Single))
	}
	x.all = all

	return val, nil
}

// WithReader tells the SingleLRU where to source values from if they don't exist in cache.
func (x *SingleLRU) WithReader(r keyvalue.SingleReader) {
	x.reader = r
}

// WithWriter tells the SingleLRU where to source values from if they don't exist in cache.
func (x *SingleLRU) WithWriter(w keyvalue.SingleWriter) {
	x.writer = w
}

// NewSingleLRU returns a new SingleLRU cache.
func NewSingleLRU(name string, i int) (*SingleLRU, error) {
	arc, err := golang_lru.NewARC(i)
	if err != nil {
		return nil, fmt.Errorf("lru: arc init - %w", err)
	}

	return &SingleLRU{
		name: name,
		lru:  arc,
	}, nil
}
