// Package cache_dal_single is generated by protoc-gen-go-genms-dal. *DO NOT EDIT*
package cache_dal_single

import (
	context "context"
	time "time"

	cache "github.com/rleszilm/genms/cache"
	keyvalue "github.com/rleszilm/genms/cmd/protoc-gen-go-genms-dal/example/single/dal/keyvalue"
	service "github.com/rleszilm/genms/service"
	stats "go.opencensus.io/stats"
	tag "go.opencensus.io/tag"
)

// SingleUpdater is an autogenerated implementation of dal.SingleUpdater.
type SingleUpdater struct {
	service.Dependencies

	name     string
	reader   keyvalue.SingleReadAller
	writer   keyvalue.SingleWriter
	key      keyvalue.SingleKeyFunc
	interval time.Duration
	done     chan struct{}
}

// Initialize initializes and starts the service. Initialize should panic in case of
// any errors. It is intended that Initialize be called only once during the service life-cycle.
func (x *SingleUpdater) Initialize(ctx context.Context) error {
	go x.update(ctx)
	return nil
}

// Shutdown closes the long-running instance, or service.
func (x *SingleUpdater) Shutdown(_ context.Context) error {
	return nil
}

// String returns the name of the updater.
func (x *SingleUpdater) String() string {
	if x.name != "" {
		return "cache-dal-single-single-updater-" + x.name
	}
	return "cache-dal-single-single-updater"
}

// NameOf returns the name of the updater.
func (x *SingleUpdater) NameOf() string {
	return x.String()
}

func (x *SingleUpdater) update(ctx context.Context) {
	ctx, _ = tag.New(ctx,
		tag.Upsert(cache.TagCollection, "single"),
		tag.Upsert(cache.TagInstance, x.name),
		tag.Upsert(cache.TagMethod, "update"),
		tag.Upsert(cache.TagType, "updater"),
	)

	ticker := time.NewTicker(1)
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			cache.Logs().Infof("starting update for %s", x.name)
			start := time.Now()
			stats.Record(ctx, cache.MeasureInflight.M(1))

			vals, err := x.reader.All(ctx)
			if err != nil {
			}

			for _, val := range vals {
				cache.Logs().Trace("updater Single storing value:", x.key(val), val)
				if _, err = x.writer.SetByKey(ctx, x.key(val), val); err != nil {
					cache.Logs().Error("updater Single could not store value:", x.key(val), val, err)
					break
				}
			}

			stats.Record(ctx, cache.MeasureInflight.M(-1))

			if err != nil {
				stats.Record(ctx, cache.MeasureError.M(1))
			}

			stop := time.Now()
			dur := float64(stop.Sub(start).Nanoseconds()) / float64(time.Millisecond)
			stats.Record(ctx, cache.MeasureLatency.M(dur))

			if x.interval == 0 {
				cache.Logs().Infof("updater %s is terminating", x.name)
				return
			}
			cache.Logs().Infof("scheduling next update for %v", x.interval)
			ticker.Reset(x.interval)
		}
	}
}

// WithReadAller tells the SingleMap where to source values from if they don't exist in cache.
func (x *SingleUpdater) WithReadAller(r keyvalue.SingleReadAller) {
	x.reader = r
}

// WithWriter tells the SingleMap where to source values from if they don't exist in cache.
func (x *SingleUpdater) WithWriter(w keyvalue.SingleWriter) {
	x.writer = w
}

// NewSingleUpdater returns a new SingleUpdater.
func NewSingleUpdater(name string, k keyvalue.SingleKeyFunc, i time.Duration) *SingleUpdater {
	return &SingleUpdater{
		name:     name,
		key:      k,
		interval: i,
		done:     make(chan struct{}),
	}
}
